# Generated by Django 5.0.2 on 2024-02-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
